sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "d7+FkiyC/YBYy1R2NvjIr/MzT976sDlGM+P6w+5Z2YU9gal6REIEeuhO/KAaZTLoIRvReKd6vQAOqmANGQyxk4NdGWT96dV2B/vA28ZLwe8MkybnqzFhEuUDeYhZXdUN+e9WbvjFabbew6XMf0drBRS1BZW2jOWO6KQtkcLqv8kLdJCMDving0AWCmKRm760LRRcvlOXB4/dLgTz7xdVwNli624KXMpMbLq88EQD0GBIhNRc6RKqgwpc0bu7PMhJdO0FrKcjD2/7OkweZIfOGbpwAEIIdmnAmxeZrnDS/XtK4YnfVx/PI3l1Oa/Rjt5mm08Pn8kk+mYjCsXD53PEb4vnxMl9p/lLTpKFX01QoTwZnhVBOfCwqzoemQtWkM6/YbUuWjV3cIasIYCr4ulqGLPSpK+nX7R8yTA/tg04izVJecEFURHlKqt8beKf+XhpYq8aR/HfRq1euxt1WpbM/icYyDkc4vYlmfIpFt5yam5EieH+qlc1OdwiTBhBY7Moi1TKsU0xsELHiYRWJyzaEFoKsWUJwwMfqV27qQ0j15KHferIrgz7pxBMcgig1hQsIyJPdKT0SWCcVCteLpgE7ebE9p1pOg0Wrj6Qe8XKxiFXB8vWGYByUHMItG0JCCN4Qv35vvQGMeDM6OhIy9aK+ikfSaa6wqWLlZwkgaVCx/Q="
branches:
  only:
  - master
