sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: NFD/pJw+XWEsGn+a3PaOTARp76gS1lrpv+6BRF754cM3VW88UPcfcpYDXTjge8pcAcFSkIgxsVEPBhIjUkSQGhG3jbHiMnALyI4FvI839rULyHdLYyYJ8ykqrTlnrP6qgr4fi01C471Xn+RNO+mPu2lPw2UfRq5GMURmpSZIVuuJ8hGw5F9DqWtUNRGFO5QPapyUBzFIHxuxKZghBmcwWToE6WLoKQfKGTt41/sa30fJGPeKBHgYVjdyrXcCb5igz0B6WkTUehk5LkKR1liZ6sU4jWBmFbuTvIXxjHgeJfegHQf59chuNN0U1jOlw3NS5xEb3cs3pTmQmXBMRSq58V8BGsQ9t3ghwmu3PkGI2pqm4EvssrBtX2XXHhU/04a2M1y7QGbntdhVewxsSU96EEcvco3UlURHTyyRIpk/QT2nuY2d2b5jQLDmWBrP46H2KCMu26fZtg8Iy8BJ9JjcIydTxg0d5tJD9E+S0NNkVgMAohbtXcoIJhWkmjGPtmH1BlYwL2g/lLxTsFwJc3y2oApd8Gdr0TfxhqCADDzjladgRlLqVjyODtRHk1FPra49E800jSLZGSNY2FMWFoL0spsNASEVhwNS9hg0Qaxpu30lIOzkXB1IZhb1En65d+Zu9Y/ejRlOCk9ciXXO68M68HUdCWNMB5Fon0Ww9gtcfGw=
branches:
  only:
  - master
