sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "NU3oCv7VWAWdN57bsg2P9abNFF2LsSmOsfRmw53exhpIQ+mop6nTTFzL45mhAGpJIX17f5HmuhaPuVB3GqNm0siRR9xFehS9IdyKnqbdTXhbEqk2xZVEFRwZg1PZ7cPnI5DBIcVAzyI1xeWje447KbxvrL46EbFX5toUnOTdTA9Aez3dSWLK101XCfbRtz5q9oo22l7V2JRCU1sjr1WZrBk6BZV7W8TjyPfX+epXnObUBlX+o9tm100NPd1FaWvHrRi0DqyXMRtXc0hsaYw7bfF80I0QmqGtlFJgO7b/HZm4VCNLwIqW3mXhVJTNLYoKN/NZEOoK4s+n9gmOdZ9uJvA4/X1TyruupVegYyRwpXzF6t2rVs/qwaV205mc7/9OmImsQIpH6+97xXlNXFcztOK5NQwhp40XrhrKAJgS099l0OhAenxkWKiCAuCph0nem2pUYoGkW8qwhZmEfiUbgjclAF9dl4vcOBnZTdJ6RuR95FqeA5BvgJkxNGvzyfn8cnQFizJyy6MF5zd6l/tGU91DE3xlkaGB/VcbLcIQASkBIuN3EiwdHbdrJdLPrSROQKIqWRhPWqx5DkqqeSmrOLo9yr8/vPC4OzT+CWZvHAQMXqpjKuRXPB0zPj6ZOdHPHFGSpZ8Swm9erkMumY5Shpadcm4C6VphjJf95LDxXZQ="
branches:
  only:
  - master
