sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install


before_script:
  - git config --global user.email "ytkim4558@naver.com"
  - git config --global user.name "ytkim4558"


script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "Dxjxex6wgF/C8aRcUP//JXCmbCViDEkxExcH5UOlL5yaK78iJPphVgacblX8UV/yyUdFYg+Bd/7F1Tq8oKM5fZJ5rt2Zzk5PpotJu0GmW/JGzKTbJGVNVml1l4XJ1lTNHIc8u9i53DzHvTE6dVxdB2QyCKjD3Kha7bBqwQMjl9zY+IsjD1um/UB5iQHIGaaQgV6koJ9xviObZ2cLQ0MYWszHSPKsrOv/8M1YNP+z8FHthJfwYfWIeivjBeSN3Wz1fYgUfljhupePLQDUgF6kYjPnoN6DFK8iV8p8nMJzcqz2SCo3VQiC1zLgpUAmxJxIS5z/4UIi+odFwEs6q26W8cclt/QMdJ6OSy0X1aPe2EU/r6Pt3P6pZ86l3C/dZptNug31M7AbCc0hWMcJbIViDieuJtxjlLEsM6tvw1JuG7XfJUVy0KsqDQSD836cpuEeTgVZ79DI7ZXnbn2XMEgOeX1IjJ+x2SClnDVUN3hK1GZdQ7MRXCQdz7SOmuTfonh0WO+6/0xp5WAgwfqNRrpa9dEQJrqWcz4o6zcmLo36uhGId7mpnG3pPSdbd2QqlnBKpqkVew5lm9huANUh38g0f+Z0EJ2n5B7mHDXj3VcGZaHdOjPDpIQtqmhsjPHnxHwIxwMVbTQI4Mg/gKSaT9VvFkA0U/WEEfBVL4DHDamcuLg="
branches:
  only:
    - master
