sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "dhGrY1v/kSRV2m86zPrJiMFnRJbHKjZ+we2sTvPLauYOAZUHl0ZvNYeNcx8ucSf7RRehPQPPjvp4Fz0DU38AOtxVI28oEs9BoxZJNELQsehDq9xjEKaaTVkzE59+PraV1RJlAeSs2e5w4Z5x0MnE+VoZw5FNaOFiQ6vZ+4nas7QKkCl4TPsOsiQzFaMyWaG/AzU/N36fc4V6CMFgcmEfbYTEPHiYCyFJnEl56myhgYshyu3ATw1hNu+ZT8EqI2XBQ/GCz0jbhCPTJ+VOGodWtakC2e4x5llmk1ncr1RM7fx+SW1oS3Y73YKlzM0ftpkFelbdHigycVySpkLYdFeFrO6zTpfCZ/H2NfBE9L5YWk2nSpRiw5JCCtM5VPs2Z9VfS7BynS2Cnbp+J0RdcDwLMN5Ww9MZk1+1AoqyIRpYjmdqP4AzOoDdpwHrNZbl3tZSr30G3fMahPLciFVAiaKNRX96InaFnnzQPQ4s9SkkUvS3YIUARgutgK5OZYUy4nBKkBdh8xwMAbmUpBp3UhftlVQDnlDkcN+MYW4Ydd3fUWw/jKw8SoBAYSkWZMkcK8scU3tLvsRLFZXj05mcu8+srMPCrHG4PgG0w1RbLvzEs/oX2h1Le0UeNhv54iXFCu3ZEfWHF2lY0xWoNCA4m4Stb5wQfvnp9/MteFCOsnpUnT4="
branches:
  only:
  - master
