sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "T6K/UJl3dX3XCjX6R4DSmv3hzszWC/J/DMOI9pjZA/ZZvEVOXEClJD0jk2P6a1E5fmRRx9FXxgxMcZIO5M3DQ3DdEhtIlAI4uUuHTnyq1iuYbTUYYRuklXb/Dr4bocPzaKjE3qpCJdgUPEWyq7iks46Zuck6iiZNmVSNieQuiCpy2/N38LFJV7+Jrz0NcBibJGoKCt/T0dprcTYK87l7jznX9s4XsJibjClN/KLizXB21E6dWXOrUEqWst0aInVb+vM6aLNhR829Uo/ePcB28Eod80+HdmJXVFLwxvfTKvH8me0jX78+y73ji1vBgeWDnR7Ive0z5MJUACM7YhZ8xm2OWv154AOINLdl7PjOvxVi0lURFlvQDF3qxUwAAP/fRld2kD6qZOY3BYU5wZEnkiFX+hyG75b/CCz2DVe0bW3Z2cfSFxvM4P8U/C7qicvVYBv5G7LO+VYyrrZCh2D4vEg2MptSqbSdNmcVGXyvkImc/Br+fGEpnztzJHhpNDkZhRz9VF4Gq8aR1bNatgDggnMsBgLsxxfVNoUNnRIIexU6DWznDeDXMIenkCw6IZ6Pcox+ssNqk0Rv9cbCo3+bRDQ2OrdUaN5YP8weZztd/hlfIBRZR3VITlf2AzpJ60js4PvBchCJaro+yyAKTG6tU61nwF8PTeUilMDrZYNXGJk="
branches:
  only:
  - master
