sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "CSUZk+4ubRg/UWIOLj/ZzO7xvI0SGs6KRcM8yRAOP2WfdDthet23ZuXeUv2p9uOoBKhTtM254AlYjSGEwTaDVNzXKSFg52hEpDZCp6keMWhELU1Q/q97Kd6CAW54WFlmauvuwno8SGEGbonTnyTdQiqTchCnOqP4I1MChOlExKp12nfb80uFL/YVHbccJlDXEqslq4GSqQ4L6b3kyl/3/uKcBN239FxAh7SJn7cfZEgCxK0F0NtmT3TpOsQsDiuMW+SWaTJKfzD9/BbrjNiI8MpWCE3lIdj2m6BW9osvhSDq4Ycnj1DxeDrmBPiq2avHqWE8RA/6SjKjx1RGNDKlakrI5PIq+tAaWhF2cUH5XnVEwyRDd2xroobsI20HoXqN3bJdceVHoQvA+xmn/A/ms1mLjjGARcvtfBozaEEQrJDPxt6dWln6INGn0hvbjCGwjrzlKOInUr7A5Z+cS+Cufr2vVOspyNTsaEM2rfSj24raCKXlioznTxTdqLM5Id1QE5QUW4XGkewKLAC5WH2q2nFUyqqcHK96QBpERgfSQkmGsux57tF8KadKs9/acTS6mBQtv9tkW/78vMQpQ48zTZ5gHnKzaRQbaozD8aAelOYKXEmAS8m3r5nrMAxKg17E1VFyyHyRCn4EMJCqLRKxaGVDr7RrNTdWM1xA3dFlOkk="
branches:
  only:
  - master
