sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global: 
branches:
  only:
  - master
dd:
  secure: o90aPAlRC6zw3Qi56IGIULTQvyY6f0lPmMP2UocUuHa3WhmM2Ze/6yGhgEFDVjkpdzLFfpGPfBgHBnAT+KChrqX2wZ2+e9YScxUsNv7hbHGGZZHtnR+RlDuItKGwlGpaeUCM3D2ivuTs7KqkuIOZtMHoqN0x5mxNdAM0kdhB9R9XwTvs5dMusovC1Yj09ftLtluhHwMt65qKunfLkMJ3+Qwh/caf+J/LlocPQcVbNIWB+0wM+2KjZ54o9QWRHTtPxFEXp6fk1JqMlnw+Mt5QcLAK02Sp246qGN7APAuvQMyvFRQyYtZMcNCzGWh4I+HCSBkq0PP6Y2crnbeJojdteyL6o9wJHqUOzFKXB6mQuH9nFJxvCf9o9wupHyNYE4ArS+Ke8twKNd2hBi255tWyJU+QJk0FWVp7s9B7KhUz7EMpv69pXNannqyAksBMfMFmzcU4mWHvDUSbJzdr8Wd+5+sNyPV3QuSq5w4Qe1Lyx+t94dTDqqJmM9OQRjrUWHRwkNKATS1AybWKSeF8y5UrZoaX03Zm+L7d15/ujT6cZWYyTSsuJN4oYm9jmrkEaDLHnVeGmy6MkOpZazcZzDIDp/N9ZP3CqZCx9NeiTw+tDHzEwEYV1aOln42JUkzdttN/BBskAduWaN1WYLaMZEUD0ODCTbP8z2GjEJS3tmaXvy4=
