sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: "jfskrHakY2MjyvxcHml/iYr9txn78/aR1oya7Bm4iCn7vwrFE5DN1/+c4mFGOgRHwALESZSZCgkFwSfT9KGdi2WlXXWYQF344006w67BHi9kVqqruzW7qMFD3MJ8N05cw8D87UKZmptteaVTdRBZS62Oh8hfUTVR9D1hGtoNVw0fv6oBBFAMD7gaF5fO8QtXyjOsJyIKi1x7GrlZuHVlgqaSKt7JeZwJIjHCmWdaSEa16TgWJs4LwYDUyyzXlpstjfkj1iykFgxhvxRXshqrG5c92UH7jWJkWkJQii4wmhtgu8H81MbLhy09FM5pIqDo8G0u2ZFMP1DlJkYnu3bWYsTgPvQeN+7Id3LNd29v5Q3fv8n2xkHYRBZmHKJLRfubP/ggG9LcgNFjgGntnYV7EejaIUGNyMWtedNyzYxaAVgul4a+vi439psGxK7EpUv/Wdu3vp6QL4BkE+Cg2jsW/mjj6bMPGOZ9jonpW7sKrcijLE56yg9qog1pvDKfZzqnA59TZk2Luken/68g4qtq6woq5RlV5vtHhENLTaiaa/waUEeQgY+ONO8qNcuB5RKyVGVT0GQsrhBI8eaOKu9xeonWt/ycISOKXDVzd7GzrVAD5UDO5BvF4sZGhyvFvPSUS9AdAB6LZ61Dx39puJxwzx9IJHC6Wne9YIW0juSKWOk="
branches:
  only:
  - master
