sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
before_script:
- git config --global user.email "ytkim4558@naver.com"
- git config --global user.name "ytkim4558"
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "Aza6tjQze54LzGvdnshl5XyVZIZzIXIUhv/YBUlSBQjD3Ig8X8ElA+X0aKOYML9tJebAceci99+zElFYby5o3sSnztRAgCvLeiMRAmhzt8Qf0phFCaxpZfFEYrYl8bZqyKTEC1SoX4LR3onq93rwGLVJsogcYiEEzauCNejQSJ2bXiyEUFYtkkC6qYCNsiGRnoAkgJvAelAl4hoVp8QjE000AR22pnqVPNAbGizbHgmAuZk5jj5o+pNj+2psj7cVZbLcsALTyIY8zM4HEO1eJtWtA0mYSeyLDl/orWqrIQC6e3z5E8Cp2nGVPpuczM39aKkJJvnDtwqD7HzWfPKBzyY9sk/uC/mdWwzGR3w6ZTHMvtbl225TCjbdXHDebgL9Pg+vq4S2e3DfdfAvrk36ShaRVmoDsbWCI6lgrGRNyb2LlmP1lF0cOeKLzNMhjDP4ZnCaZbvaqSTbmzXtzPZkg+g4tMmOAbQMiw3qKa0yz2w/IAzJnXRJU/PWJ+9yT2GI1EGXRLYy/l3zHijNWlW6thR9nttkPVv5MnVX7vT+5pa41T38CXdnFxk4yNGiMwen5OfPiRnKvGm87CmaOunOipE5pdc0Dp4+9H4JdD6cC40we919ezJJ7N/VyTpb2edDcXEBOq2Sjqn9fVgpfe2RvfPqvwVXTY9KKD56E1+WDwk="
branches:
  only:
  - master
